### ISSUE TITLE
livereload and typescript 

### ISSUE THREAD

**Issue by dispbd** [totaljs/framework4#27]
Hello.
We are using typescript when working with Total.js.
Everything is configured as in the example, and it works fine, except for one thing - in `debug mode` and `options.livereload = true` in the startup file, when the project changes, the server does not reboot (as a result, the client too).
If `options.livereload = false`, then restarting the server works, but this is not very convenient, since I would like the client to restart automatically as well. I repeat that this is precisely with typescript, when splicing through regular js, there is no such problem.
I suspect there are two reasons - either livereload does not take into account .ts files in the function where it is checked, or the typescript does not compile this function correctly.

Any ideas how to fix it?

**Comment by petersirka** [comment]
Hi @dispbd,
I have fixed the live reload. Can you test it? Because personally, I don't use TypeScript.

- `$ npm install total4@beta`
- I have created a new example `livereload` <https://github.com/totaljs/examples/tree/master/livereload>, but it will work only with the Total.js 4 beta version

Please let me know if it will work.

**Comment by dispbd** [comment]
Everything works fine.
As always, thanks for the promptness!
